use_frameworks!

platform :ios, '10.0'

target 'LCXInformationFlowView_Example' do
  pod 'LCXInformationFlowView', :path => '../'
  
  pod 'Masonry'
  pod 'MJRefresh'

  target 'LCXInformationFlowView_Tests' do
    inherit! :search_paths

    
  end
end
