use_frameworks!

platform :ios, '10.0'

target 'LCXInformationFlowView_Example' do
  pod 'LCXInformationFlowView', :path => '../'

  target 'LCXInformationFlowView_Tests' do
    inherit! :search_paths

    
  end
end
